### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Maximapple** [bernardphh/500px-APIless#1]
![image](https://user-images.githubusercontent.com/5410641/74223351-c4ef5700-4cb6-11ea-8442-29e284d59b23.png)

That's what happens when I double-click the file.

**Comment by bernardphh** [comment]
Fixed syntax warnings on comparing string with None.
Thanks for reporting.

**Comment by Maximapple** [comment]
Thanks, it works now.

Any way you can make it so that the feature #9 can like more than 100 pictures at once? it asks me for an amount but no matter what I type it will always only do 100. (fresh gallery)

**Comment by bernardphh** [comment]
This is a feature that I call #self limitation to avoid abusing.
Anyway, if you want to push it, go to the file config.py and change 100 to any number
MAX_AUTO_LIKE_REQUEST    = 100

**Comment by Maximapple** [comment]
Thanks.

Maybe you can make it so that it shows what the current max amount is when it asks you how many pictures you want to like.

This can prevent confusion ^ :)

**Comment by bernardphh** [comment]
Thank you Maxim. No one likes being confused ! : ). I will make it clearer.
