### ISSUE TITLE
it dosnt work on linux

### ISSUE THREAD

**Issue by allVentures** [bernardphh/500px-APIless#2]
how do we make it work?
the "msvcrt' is not defined"
this module works only on Win

**Comment by bernardphh** [comment]
This thing is indeed for Windows:
_"This was developed using Visual Studio Code, testing and run on Windows 10, Python version 3.6"_
Sorry to disappoint you.

**Comment by bernardphh** [comment]
If time and resource permit,  I'd love to do some changes to make the script work in other environments (linux, android and ios). So I will close this issue now.
